# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: TeamsClone_Project CI

on:
  push:
    branches: [ meghna ]
  pull_request:
    branches: [ meghna ]

jobs:
  tests:
    name: running-unit-tests
    runs-on: ubuntu-latest


    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - name: install-modules
      run: npm install
    - run: npm ci
    - run: npm run build --if-present
    - name: test
      run: npm test
      env:
      CI: true
